# Generated by Django 4.0.6 on 2022-12-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('date_built', models.DateField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.airline')),
            ],
            options={
                'unique_together': {('airplane_id', 'airline')},
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('airport_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('password_hash', models.CharField(max_length=256)),
                ('password_salt', models.CharField(max_length=256)),
                ('building_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=10)),
                ('passport_expiration', models.DateField()),
                ('passport_country', models.CharField(max_length=2)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='website.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='website.airport')),
            ],
            options={
                'unique_together': {('airline', 'flight_number')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_type', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('security_code', models.CharField(max_length=4)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.flight')),
            ],
        ),
        migrations.CreateModel(
            name='AirlineStaff',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=256)),
                ('password_salt', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.airline')),
            ],
        ),
    ]
