# Generated by Django 4.0.6 on 2022-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_flight_arrival_date_flight_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(default='On Time', max_length=30),
            preserve_default=False,
        ),
    ]
